### ISSUE TITLE
Job List Endpoint

### ISSUE THREAD

**Issue by xcomagent95** [xcomagent95/RichDataInterfacesForCopernicusData#28]
Implementieren des Job List Endpoints:

- [x] Requirement 64: The server SHALL support the HTTP GET operation at the path /jobs
- [x] Requirement 65: The operation SHALL support a parameter type with the following characteristics (using an OpenAPI Specification 3.0 fragment)
```
name: type
in: query
required: false
schema:
  type: array
  items:
    type: string
```
- [x] Requirement 66: If the parameter is provided and its value is process then only jobs created by an OGC processes API SHALL be included in the response & If the parameter is omitted, then all jobs SHALL be included in the response
- [x] Requirement 67: If the server supports this conformance class, the optional processID property in the [statusInfo.yaml](http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/statusInfo.yaml) schema SHALL be mandatory
- [x] Requirement 68: The operation SHALL support a parameter processID with the following characteristics (using an OpenAPI Specification 3.0 fragment)
```
name: processID
in: query
required: false
schema:
  type: array
  items:
    type: string
```
- [x] Requirement 69: If the parameter is specified with the operation, only jobs that have a value for the processID property (see: [statusInfo.yaml](http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/statusInfo.yaml)) that matches one of the values specified for the processID parameter SHALL be included in the response
- [x] Requirement 70: The operation SHALL support a parameter status with the following characteristics (using an OpenAPI Specification 3.0 fragment)
```
name: status
in: query
required: false
schema:
  type: array
  items:
    type: string
```
- [x] Requirement 71: If the parameter is specified with the operation, only jobs that have a value for the status property (see: [statusInfo.yaml](http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/statusInfo.yaml)) that matches one of the specified values of the status parameter SHALL be included in the response
- [x] Requirement 72: 
- A: The operation SHALL support a parameter datetime with the following characteristics (using an OpenAPI Specification 3.0 fragment)
```
name: datetime
in: query
required: false
schema:
  type: string
```
- B: The value of the datetime parameter is either a date-time value or a time interval. The parameter value SHALL conform to the following syntax (using [ABNF](https://tools.ietf.org/html/rfc2234))
```
interval-closed     = date-time "/" date-time
interval-open-start = [".."] "/" date-time
interval-open-end   = date-time "/" [".."]
interval            = interval-closed / interval-open-start / interval-open-end
datetime            = date-time / interval
```
- C: The syntax of date-time is specified by [RFC 3339, 5.6](https://tools.ietf.org/html/rfc3339#section-5.6)
- D: Open ranges in time intervals at the start or end are supported using a double-dot (..) or an empty string for the start/end
- [x] Requirement 73: If the parameter is specified with the operation, only jobs that have a value for the created property (see: [statusInfo.yaml](http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/statusInfo.yaml) that intersects the temporal information in the datetime parameter SHALL be included in the response
- [x] Requirement 74: 
- A: The operation SHALL support a parameter minDuration with the following characteristics (using an OpenAPI Specification 3.0 fragment)
```
name: minDuration
in: query
required: false
schema:
  type: array
  items:
    type: integer
```
- B: The operation SHALL support a parameter maxDuration with the following characteristics (using an OpenAPI Specification 3.0 fragment)
```
name: maxDuration
in: query
required: false
schema:
  type: array
  items:
    type: integer
style: form
explode: false
```
- [x] Requirement 75:
- Conditions: If the status parameter is not specified then only jobs that are running (status: running) or have completed execution (successful, failed or dismissed) SHALL be considered for inclusion in the response & If the status parameter is specified, then only jobs with the specified status SHALL be considered for inclusion in the response
- A: If only the minDuration parameter is specified with the operation, only jobs with the appropriate status and a duration of at least the specified minDuration value SHALL be included in the response
- B: If only the maxDuration parameter is specified with the operation, only jobs with the appropriate status and a duration of no longer than the specified maxDuration value SHALL be included in the response 
- C: If both the minDuration and maxDuration parameters are specified with the operation, only jobs with the appropriate status and a duration of at least the specified minDuration value and no longer than the specified maxDuration value SHALL be included in the response
- D: The value of the minDuration and maxDuration parameters SHALL be number of seconds
- E: For running jobs, the duration SHALL be computed at runtime as the time the operation was invoked minus the value of the started parameter (see: [statusInfo.yaml](http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/statusInfo.yaml))
- F: For completed jobs, the duration SHALL be computed as the value of the finished parameter minus the value of the started parameter (see: [statusInfo.yaml](http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/statusInfo.yaml))
- G: Jobs for which runtime statistics are not included in the [status information](http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/statusInfo.yaml) or are incomplete for computing the duration of the job SHALL be omitted from the response
- [x] Requirement 76: The operation SHALL support a parameter limit with the following characteristics (using an OpenAPI Specification 3.0 fragment)
```
name: limit
in: query
required: false
schema:
  type: integer
  minimum: 1
  maximum: 10000
  default: 10
```
- [x] Requirement 77:
- A: The response SHALL not contain more jobs than specified by the optional limit parameter
- B: If the API definition specifies a maximum value for limit parameter, the response SHALL not contain more jobs than this maximum value
- [x] Requirement 78: A successful execution of the operation SHALL be reported as a response with a HTTP status code 200. The content of that response SHALL be based upon the OpenAPI 3.0 schema [jobList.yaml](http://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/jobList.yaml)
```
type: object
required:
  - jobs
  - links
properties:
  jobs:
    type: array
    items:
      $ref: "statusInfo.yaml"
  links:
    type: array
    items:
      $ref: "link.yaml"
```
- [x] Requirement 79: A 200-response SHALL include the following links:
- a link to this response document (relation: self)
- a link to the response document in every other media type supported by the service (relation: alternate)
